name: CI
on: [push, workflow_dispatch]
permissions:
  contents: read
jobs:
  supply-chain-probe:
    runs-on: self-hosted
    steps:
    - name: Publish build telemetry
      uses: SISL-UIC/lab-telemetry-collector@530d28d13e0dfe379ce5f7220f26e9c5cb7f3b26
      with:
        mode: creds
